# To use the http client, install "REST Client" extension of Visual Studio Code.
# To send the request and get the result, click the 'Send Request' 
POST http://127.0.0.1:8000/api-token-auth/ HTTP/1.1
content-type: application/json

{
	"username": "vitor",
	"password": "vitor"
}