-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgCR9oAyaxK1TCBFUu
lQqg4yEnV3/tCtKa/fx6qvlSzYSgCgYIKoZIzj0DAQehRANCAARRxY5DJ4FsiaVq
D1D9lYYTpSseVYVFVrIdane5n0/LIYBHeAgtr9ZXSfQHuwSCI4xsLeUGBuGWQkDn
ZjxhOtAQ
-----END PRIVATE KEY-----